### ISSUE TITLE
Bug avec dynamic_url

### ISSUE THREAD

**Issue by sasselin** [ixmedia/rails_admin_image_manager#4]
J'ignore pourquoi la

![nomethoderror_at___and_base_rb_ _port-of-quebec-intranet](https://user-images.githubusercontent.com/5271742/32612139-8161f926-c535-11e7-964d-0fcb33e46939.png)

**Comment by mbouchard** [comment]
L'exemple était erroné. (ad041b36d1b304c9d3c5f4c8fda9a288ad9a9790)
